### PR TITLE
-

### PR DESCRIPTION
**Pull request by HausemasterIssue**
idk where to contact you but...

doogie bro i need some help with strafe in spidersense. i tried taking ur advice but the doublesetting fucks with the playerspeed double, could you help me out by making a pr on spidersense with the proper code?

### CODE REVIEW

**Comment by HausemasterIssue** [comment]
hi tiger this is awkward i just need doogie13 to help me a bit :)

**Comment by ghost** [comment]
Please contact doogie elsewhere, this github isnt a chat platform

**Comment by HausemasterIssue** [comment]
> 
> 
> Please contact doogie elsewhere, this github isnt a chat platform

so sorry bro.

**Comment by HausemasterIssue** [comment]
and i did fix my problem so sorry for this guys.

**Pull request closed without merging**
