### PR TITLE
Add LagNotifier module

### PR DESCRIPTION
**Pull request by girlfangs**
**Changes proposed in this pull request:**
Adds a LagNotifier module that prints a chat message when the client has not received a packet for a certain amount of client ticks.
Probably behaves weirdly when using Timer.

### CODE REVIEW

**Comment by Tigermouthbear** [comment]
I think it would be better to render the notice at the top of the screen or something similar. Also its missing a forge version, I can make those improvements if you want or you can. Lmk what you think

**Comment by girlfangs** [comment]
I actually did think about rendering to the top of the screen but I couldn't find a way to do it, so I just settled for printing to chat.
This should be portable to forge as is right? I can try to port it if needed.

**Comment by ghost** [comment]
Or maybe just add it as an element to the HUD module?

**Comment by girlfangs** [comment]
That sounds like a good idea, but should I keep the printing to chat option and let the user choose or should I just replace it with an overlay? In that case, do I move the module to the HUD category or do I keep it on Misc?

**Comment by octoshrimpy** [comment]
I'd keep it in hud and give the user a choice. technically chat is a hud, just vanilla.

**Comment by girlfangs** [comment]
I tried my best on the HUD module, should work fine, however I don't know what to use as defaults on the super() call, so I just put some dummy values. Feel free to make any improvements or changes.

**Pull request merged**
