### PR TITLE
Rewrote PacketFly and Speed

### PR DESCRIPTION
**Pull request by Doogie13**
**Fixes #.**
N/A

**Changes proposed in this pull request:**
Removed old Strafe in place of Speed module with new Strafe and YPort modes
ReWrote packetfly to actually work

**Additional context**
Untested on Fabric-1.16 but forge 1.12.2 and fabric 1.17.1 are tested

### CODE REVIEW

**Comment by Doogie13** [comment]
this fail happened to me. i just commented out lines 42, 43 because i didnt need the installer. no idea why it happens tho

**Comment by IUDevman** [comment]
🙏 Pray for tiger

**Comment by B2H990** [comment]
I have physical pain from reading this.

**Comment by Tigermouthbear** [comment]
Ok, I'll fix the installer and squash your commits

**Comment by Tigermouthbear** [comment]
this was squashed and rebased (very scuffed lol), Github wont mark it as merged tho bc its stupid. Im just closing it manually

**Comment by Doogie13** [comment]
lol

**Pull request closed without merging**
